# Site settings
title: 'Joshua McLucas - Actor, Director, Developer'
email: jtmclucas13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The home base for the most exciting theater/web artist in Philadelphia (self-described).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.joshuamclucas.com" # the base hostname & protocol for your site
twitter_username: joshmclucas
github_username:  jtmclucas13

# Build settings
markdown: kramdown
